### ISSUE TITLE
it's not working 100%

### ISSUE THREAD

**Issue by sdsucks** [angelsl/misc-Scripts#6]
it works on some videos but not on others.
probably youtube has changed something again.

https://www.youtube.com/watch?v=S5hcTDV6j28

**Comment by angelsl** [comment]
Are you talking about 2160p?

**Comment by sdsucks** [comment]
no, i mean i don't even see the button on some videos

**Comment by angelsl** [comment]
Can you give me a video that fails completely?

**Comment by sdsucks** [comment]
i don't see the button on the link in the first post.
1 more example:
https://www.youtube.com/watch?v=lFunkva-SHk

tested with opera stable/beta/developer, chrome64, firefox64 and maxthon.

**Comment by angelsl** [comment]
Both videos work fine for me.
![2015-01-31_19-43-05](https://cloud.githubusercontent.com/assets/235432/5987928/780057ec-a981-11e4-82ba-de4d8327c474.png)
![2015-01-31_19-43-56](https://cloud.githubusercontent.com/assets/235432/5987931/83f9108e-a981-11e4-8edf-c1714b1110dd.png)

**Comment by sdsucks** [comment]
weird. i just installed ff 35.0.1 x86 (i'm on win7 x64) and i don't see the button on both videos.
now i'm even more confused what is causing this. it used to work just fine with all my browsers until a few days ago.
anyway just fyi, i tested with these browsers;
Opera Stable 27.0.1689.54
Opera beta 27.0.1689.44
Opera Dev. 28.0.1750.5
Chrome 41.0.2272.35(x64)
Firefox 36.0b5(x64)
Maxthon beta 4.4.4.600

**Comment by angelsl** [comment]
Check your browser console, are there any errors from the userscript?

Ctrl+Shift+J on Firefox.

**Comment by sdsucks** [comment]
v1.76..2 solves the problem
