### ISSUE TITLE
your script misses some formats on some videos

### ISSUE THREAD

**Issue by sdsucks** [angelsl/misc-Scripts#8]
sample: https://www.youtube.com/watch?v=FIl7x6_3R5Y

please take a look at this;
https://github.com/rg3/youtube-dl/pull/6097

**Comment by angelsl** [comment]
I'll work on this sometime next week. My script desperately needs to be rewritten. (Oops)

Thanks for the report.

**Comment by angelsl** [comment]
I'll probably decompile the Flash player too and find out how it gets its data. Last I checked Google didn't obfuscate it.
